version: '3'

services:
  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
      - "8080:80"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles
