version: '3'

services:
  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles
      - ./certbot/conf:/etc/letsencrypt
