version: '3'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    container_name: celery_worker
    image: celery:latest
    environment:
      - DJANGO_SETTINGS_MODULE=web.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A web worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  celery_beat:
    container_name: celery_beat
    image: celery:latest
    environment:
      - DJANGO_SETTINGS_MODULE=web.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A web beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./static:/app/static
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - redis

volumes:
  redis_data:
      driver: local
