version: '3'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    container_name: celery_worker
    build:
      context: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A acuarius worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_beat:
    container_name: celery_beat
    build:
      context: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A acuarius beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  web:
    container_name: web
    build: .
    env_file:
      - .env
    environment:
      - NGINX_CONFIG=${NGINX_CONFIG}
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./static:/app/static
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles
      - ./certbot/conf:/etc/letsencrypt
    command: >
      sh -c "service nginx start && gunicorn acuarius.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - redis

volumes:
  redis_data:
      driver: local
