# Generated by Django 4.2.4 on 2023-08-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Nombre')),
                ('img_small', models.CharField(max_length=125, verbose_name='Imagen pequeña')),
                ('img_large', models.CharField(max_length=125, verbose_name='Imagen grande')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
