# Generated by Django 4.2.4 on 2023-08-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img_large',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen grande'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img_small',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen pequeña'),
        ),
    ]
